# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days 2014'
tagline:          'A workshop for GAP developers and users'
description:      'A workshop for <a href="http://www.gap-system.org/">GAP</a> developers and users.'
url:              http://gapdays2014.coxeter.de/
baseurl:          /

#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/fingolfin/gapdays2014
