# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days 2014'
tagline:          'A workshop for GAP developers and users'
description:      'August 25-29, 2014'
url:              http://gapdays.de
baseurl:          /gapdays2014


exclude: [ "LICENSE.hyde.md", "README.hyde.md", "gapday2014-program.*", "misc" ]
include: [ "gapday2014-program.pdf" ]
